-- Revoke database roles and privileges
-- Cleanup before login deletion

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM :'DBUSERNAMES';
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM :'DBUSERNAMES';
REVOKE ALL PRIVILEGES ON DATABASE :'CURRENT_DATABASE' FROM :'DBUSERNAMES';
